Repository allo-protocol/allo-v2, pull requests merged in 2023-11, with the labels that each got.

#415 fix: impact stream recipientId
  contracts/strategies/_poc/qv-impact-stream/QVImpactStreamStrategy.sol
  test/foundry/strategies/QVImpactStreamStrategyTest.t.sol
Labels: do not merge

#416 Remove check on register recipient
  contracts/strategies/_poc/qv-impact-stream/QVImpactStreamStrategy.sol
  test/foundry/strategies/QVImpactStreamStrategyTest.t.sol
Labels: urgent

#418 Update readme with latest deploy
  contracts/DEPLOYMENTS.md
  contracts/deployments/goerli/DEPLOYMENTS.md
  contracts/deployments/optimism-goerli/DEPLOYMENTS.md
  contracts/deployments/sepolia/DEPLOYMENTS.md
Labels: documentation
